### PR TITLE
Fix #159: Fixed string interpolation format for php 8.2

### PR DESCRIPTION
**Pull request by qwerty199369**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  |

### CODE REVIEW

**Comment by terabytesoftw** [comment]
Would you like to resolve it in a PR?

**Comment by qwerty199369** [comment]
Done.

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
:+1: Please add a line for CHANGELOG. Thanks.

**Comment by qwerty199369** [comment]
CHANGELOG.md updated :)

**Review by terabytesoftw — APPROVED** [review]

**Review by rhertogh — APPROVED** [review]

**Comment by samdark** [comment]
Thank you!

**Pull request merged**
