### PR TITLE
prevent twig 3.9 from installing

### PR DESCRIPTION
**Pull request by schmunk42**
see also https://github.com/yiisoft/yii2-twig/pull/154#issuecomment-2072084005 and following

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | #153 (workaround)

Should be removed when lib is updated to work correctly with twig 3.9

### CODE REVIEW

**Comment by schmunk42** [comment]
Should be merged and released as `2.4.3`.

Compatibility with `twig 3.9` should be released as `2.5.0` IMHO.

**Review by samdark — APPROVED** [review]

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Thanks!

**Comment by schmunk42** [comment]
Could you also create a release `2.4.3`?

**Comment by schmunk42** [comment]
@samdark PS: There were no PHP code changes since 2.4.2 https://github.com/yiisoft/yii2-twig/compare/2.4.2...master

**Pull request merged**
