### PR TITLE
Add function __isset, for get the value of the static variable in the template

### PR DESCRIPTION
**Pull request by mrlinqu**
For get the value of the static variable in the twig template

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | no

### CODE REVIEW

**Comment by samdark** [comment]
Please add a line for changelog.

**Comment by mrlinqu** [comment]
> Please add a line for changelog.
Sorry, I am newby. How to do that?

**Comment by samdark** [comment]
Add another commit with the changes to the same branch.

**Comment by mrlinqu** [comment]
Sorry, I don't understand: add line to CHANGELOG.md file? Format of this line - version, bug num?

**Comment by samdark** [comment]
Yes. Format is `- Enh #78: your changelog line here (mrlinqu)`

**Comment by samdark** [comment]
Merged. Thank you!

**Pull request merged**
