### PR TITLE
fixed HtmlHelperExtension issue

### PR DESCRIPTION
**Pull request by boliver20**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #103

### CODE REVIEW

**Comment by samdark** [comment]
Seems to fail tests.

**Comment by boliver20** [comment]
> Seems to fail tests.

Yes, unfortunately, the code is not compatibility for Twig 2.7+.
Maybe I put >=2.0 <2.7 restrict in composer.json?

**Comment by boliver20** [comment]
> Looks good. A line for changelog is needed.

Sorry, I added.

**Comment by samdark** [comment]
Merged. Good job 👍 

I'm going to release 2.2.2 and then proceed with another pull request.

**Pull request merged**
